# Generated by Django 4.0.4 on 2022-08-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Skill',
            new_name='Skills',
        ),
    ]
