# Generated by Django 4.0.4 on 2022-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_rename_skill_skill_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='EndDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='StartDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='EndDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='StartDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
    ]
