# Generated by Django 4.0.4 on 2022-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_alter_education_enddate_alter_education_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
