# Generated by Django 4.0.4 on 2022-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=5),
        ),
    ]
