# Generated by Django 4.0.4 on 2022-08-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='IsContinue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='IsContinue',
            field=models.BooleanField(default=False),
        ),
    ]
