# Generated by Django 4.0.4 on 2022-08-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_education_iscontinue_experience_iscontinue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Description',
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('40', 'Basic'), ('60', 'Intermediate'), ('100', 'Advance')], max_length=10),
        ),
    ]
